with LOCATION as (
select _row,time_zone,LATITUDE,TOTAL_REGENCIES,TOTAL_RURAL_VILLAGES,LOCATION_ISO_CODE,
    POPULATION_DENSITY,POPULATION,TOTAL_DISTRICTS,TOTAL_CITIES,ISLAND,
    LONGITUDE,DATE,PROVINCE,SPECIAL_STATUS,TOTAL_URBAN_VILLAGES,COUNTRY,LOCATION_LEVEL,AREA_KM_2_,LOCATION
    CONTINENT
    from {{source("GOOGLE_SHEETS","COVID_19_INDONESIA_MAHESH_PRASAD")}}
)
select * from LOCATION

